2020-06-12 10:38:01,410 ERROR 3842 [-/::1/-/4ms GET /api/role/routes?id=1] nodejs.TypeError: Cannot read property 'checkData' of undefined
    at RoleController.getOne (/Users/yuakira/dev/projects/Psychology2/app/controller/role.js:87:36)
    at Object.callFn (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:45:18)
    at /Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:44:32)
    at /Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at responseOption (/Users/yuakira/dev/projects/Psychology2/app/middleware/responseOption.js:11:19)
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at isLogin (/Users/yuakira/dev/projects/Psychology2/app/middleware/isLogin.js:12:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/yuakira/dev/projects/Psychology2/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-session/index.js:41:7)

pid: 3842
hostname: yudeMacBook-Pro.local

2020-06-12 10:39:08,190 ERROR 3902 [-/::1/-/23ms GET /api/role/routes?id=1] nodejs.TypeError: service.role.getOne is not a function
    at RoleController.getOne (/Users/yuakira/dev/projects/Psychology2/app/controller/role.js:90:37)
    at Object.callFn (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:45:18)
    at /Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:44:32)
    at /Users/yuakira/dev/projects/Psychology2/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at responseOption (/Users/yuakira/dev/projects/Psychology2/app/middleware/responseOption.js:11:19)
    at dispatch (/Users/yuakira/dev/projects/Psychology2/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at isLogin (/Users/yuakira/dev/projects/Psychology2/app/middleware/isLogin.js:12:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/yuakira/dev/projects/Psychology2/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yuakira/dev/projects/Psychology2/node_modules/koa-session/index.js:41:7)

pid: 3902
hostname: yudeMacBook-Pro.local

2020-06-12 11:16:41,407 ERROR 3837 nodejs.ClusterClientNoResponseError: client no response in 440431ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3837
hostname: yudeMacBook-Pro.local

2020-06-12 12:40:07,335 ERROR 3837 nodejs.ClusterClientNoResponseError: client no response in 2743170ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3837
hostname: yudeMacBook-Pro.local

2020-06-12 14:15:43,314 ERROR 3837 nodejs.ClusterClientNoResponseError: client no response in 954879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3837
hostname: yudeMacBook-Pro.local

2020-06-12 14:43:58,142 ERROR 3837 nodejs.ClusterClientNoResponseError: client no response in 1694808ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3837
hostname: yudeMacBook-Pro.local

2020-06-14 18:24:51,316 ERROR 5213 nodejs.ClusterClientNoResponseError: client no response in 2261237ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 5213
hostname: yudeMacBook-Pro.lan

2020-06-14 19:00:14,704 ERROR 5213 nodejs.ClusterClientNoResponseError: client no response in 2083385ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 5213
hostname: yudeMacBook-Pro.lan

2020-06-14 20:20:02,563 ERROR 5213 nodejs.ClusterClientNoResponseError: client no response in 4747848ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 5213
hostname: yudeMacBook-Pro.lan

2020-06-15 01:16:20,281 ERROR 6982 nodejs.ECONNREFUSEDError: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 (uncaughtException throw 1 times on pid:6982)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 6982
hostname: yudeMacBook-Pro.lan

2020-06-15 01:16:20,631 ERROR 6982 nodejs.ECONNREFUSEDError: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 (uncaughtException throw 2 times on pid:6982)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 6982
hostname: yudeMacBook-Pro.lan

2020-06-15 01:16:21,213 ERROR 6982 nodejs.ECONNREFUSEDError: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 (uncaughtException throw 3 times on pid:6982)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 6982
hostname: yudeMacBook-Pro.lan

2020-06-15 01:16:22,202 ERROR 6982 nodejs.ECONNREFUSEDError: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 (uncaughtException throw 4 times on pid:6982)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 6982
hostname: yudeMacBook-Pro.lan

2020-06-15 01:16:23,880 ERROR 6982 nodejs.ECONNREFUSEDError: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 (uncaughtException throw 5 times on pid:6982)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
errno: "ECONNREFUSED"
code: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 6982
hostname: yudeMacBook-Pro.lan

2020-06-15 10:36:02,867 ERROR 4618 nodejs.unhandledRejectionError: controller not exists
    at resolveController (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/egg_router.js:298:26)
    at spliteAndResolveRouterParams (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/egg_router.js:277:20)
    at EggRouter.<computed> [as get] (/Users/yuakira/dev/projects/Psychology2/node_modules/@eggjs/router/lib/egg_router.js:72:25)
    at module.exports (/Users/yuakira/dev/projects/Psychology2/app/router.js:46:10)
    at AppWorkerLoader.loadFile (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-core/lib/loader/egg_loader.js:304:13)
    at AppWorkerLoader.loadRouter (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-core/lib/loader/mixin/router.js:17:10)
    at AppWorkerLoader.load (/Users/yuakira/dev/projects/Psychology2/node_modules/egg/lib/loader/app_worker_loader.js:43:10)
    at new Application (/Users/yuakira/dev/projects/Psychology2/node_modules/egg/lib/application.js:66:19)
    at Object.<anonymous> (/Users/yuakira/dev/projects/Psychology2/node_modules/egg-cluster/lib/app_worker.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
name: "unhandledRejectionError"
pid: 4618
hostname: yudeMacBook-Pro.local

2020-06-15 10:52:36,049 ERROR 3335 nodejs.ClusterClientNoResponseError: client no response in 438869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3335
hostname: yudeMacBook-Pro.local

2020-06-15 10:57:14,314 ERROR 3335 nodejs.ClusterClientNoResponseError: client no response in 258245ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yuakira/dev/projects/Psychology2/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 3335
hostname: yudeMacBook-Pro.local

